### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [viWiD/Evergreen#15]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by nilsvu** [comment]
Hey @lfarah, I'm going to update ASAP.

**Comment by nilsvu** [comment]
Hi @lfarah, I merged @Bouke's #14 to move to Swift 3 and also adopted the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) in the process. Please try the latest version and let me know your thoughts.

Also I'd very much appreciate some general feedback on the framework. Do you find the functionality useful? How would you compare Evergreen to other logging frameworks you may have tried? Do you agree with the architecture and public API choices? Anyone, please feel free to comment, open more issues or drop me a message via Email or [Twitter](https://twitter.com/knlyy) :)

Cheers,
Nils

**Comment by Bouke** [comment]
@knly I've worked a lot with Python's `logging` library before. Seeing that this project's API is inspired by that library, I really appreciate how it works. 👍
